spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
