openapi: 3.0.1
info:
  version: 1.0.0
  title: Customer API
  description: A Simple API to illustrate OpenAPI concepts 

servers:
- url: https://localhost:8080
  description: Development Setup
tags: 
- name: customer
  description: Customer information 
- name: customerType
  description: Supporting customer types Retail,Coporate, Guest

paths:
  /customer:
    post:
      tags:
      - customer
      summary: Add a new customer
      operationId: addCustomer
      requestBody:   
        description: customer object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/xml:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        400:
          description: Invalid input
          content: {}

  /customer/getAll:
    get:
      tags:
      - customer
      summary: Retreiece all customers 
      operationId: getAllCustomers
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'            
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        joinedDate:
          type: string
          format: date-time
        type:
          type: string
          description: type of the customer
          enum:
          - Corporate
          - Retail
          - Guest
          